# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2831e7186a9b3d9e2d7fd69dc38020332e4e57aae993a8bb8fccfc8a1183e659a82d24a89f3db0ba2f82eb7b4821ccc549b14e8c4f1865dfbd2212a404f95354

test:
  secret_key_base: 6b6231e56d9bd370bed49067ca8738f4a53957c067758805c99caf66e0888de5b443480b3d021af7851a56becd5cc316d8ed2ea3c2a9a159c3f7fcb01f1ccdbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
